# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 01:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='试卷名称')),
                ('num', models.IntegerField(default=0, verbose_name='题目数量')),
                ('level', models.CharField(choices=[('easy', '简单'), ('middle', '中等'), ('hard', '困难')], max_length=10)),
                ('student', models.IntegerField(default=0, verbose_name='已做人数')),
                ('like', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='题目内容')),
                ('answer', models.CharField(max_length=4, verbose_name='标准答案')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('papers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Paper', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='类型名')),
                ('instr', models.CharField(max_length=100, verbose_name='介绍')),
                ('click', models.IntegerField(default=0, verbose_name='点击人数')),
                ('image', models.ImageField(upload_to='type/%Y/%m', verbose_name='类型图片')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper.Type', verbose_name='试卷'),
        ),
        migrations.AddField(
            model_name='answer',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='paper.Topic', verbose_name='答案'),
        ),
    ]
