# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='is_tab',
            field=models.BooleanField(default='False', help_text='是否导航', verbose_name='是否导航'),
        ),
        migrations.AddField(
            model_name='type',
            name='parents',
            field=models.ForeignKey(blank=True, help_text='父类目级别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='paper.Type', verbose_name='父类目级别'),
        ),
        migrations.AddField(
            model_name='type',
            name='type_s',
            field=models.IntegerField(choices=[(1, '一级目录'), (2, '二级目录')], default=0, help_text='类目级别', verbose_name='类目级别'),
        ),
        migrations.AlterField(
            model_name='type',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='type',
            name='click',
            field=models.IntegerField(default=0, help_text='点击人数', verbose_name='点击人数'),
        ),
        migrations.AlterField(
            model_name='type',
            name='image',
            field=models.ImageField(help_text='类型图片', upload_to='type/%Y/%m', verbose_name='类型图片'),
        ),
        migrations.AlterField(
            model_name='type',
            name='instr',
            field=models.CharField(help_text='介绍', max_length=100, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(help_text='类型名', max_length=10, verbose_name='类型名'),
        ),
    ]
