# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20180113_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='code',
            field=models.CharField(default='', help_text='类型code', max_length=10, verbose_name='类型code'),
        ),
    ]
