# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_type_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': '试卷类型', 'verbose_name_plural': '试卷类型'},
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(default='', help_text='类型名', max_length=10, verbose_name='类型名'),
        ),
    ]
