# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_auto_20180113_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='parents',
            field=models.ForeignKey(blank=True, help_text='父类目级别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='paper.Type', verbose_name='父类目级别'),
        ),
    ]
