# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0005_auto_20180113_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='paper.Topic', verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paper.Type', verbose_name='试卷'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='papers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paper.Paper', verbose_name='题目'),
        ),
    ]
