# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0007_auto_20180114_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
