# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0008_type_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='is_parents',
            field=models.BooleanField(default='False', verbose_name='是否为父级目录'),
        ),
    ]
