# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0009_type_is_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='instr',
            field=models.TextField(help_text='介绍', max_length=100, verbose_name='介绍'),
        ),
    ]
