# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0011_auto_20180226_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=2, verbose_name='选项'),
        ),
        migrations.AddField(
            model_name='topic',
            name='num',
            field=models.CharField(default=0, help_text='题目num', max_length=2, verbose_name='题目num'),
        ),
    ]
