# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180114_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlike',
            name='like_type',
            field=models.IntegerField(choices=[(1, '类型'), (2, '试卷')], default=2, help_text='收藏类型', verbose_name='收藏类型'),
        ),
    ]
