# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 16:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180110_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='轮播图', upload_to='banner/%Y/%m', verbose_name='轮播图'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='index',
            field=models.IntegerField(default=100, help_text='顺序', verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(help_text='访问地址', verbose_name='访问地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', help_text='性别', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', help_text='图片', upload_to='userprofile/images', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(help_text='手机号码', max_length=11, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(help_text='验证码', max_length=10, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(help_text='电话', max_length=11, verbose_name='电话'),
        ),
    ]
