# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.jpg', help_text='图片', upload_to='image/%Y%m', verbose_name='图片'),
        ),
    ]
